import type { Metadata } from "next";
import Link from "next/link";

import { ContentSection } from "@/components/ContentPage";
import { LegalPageShell } from "@/components/LegalPageShell";

export const metadata: Metadata = {
  title: "Engineering Disclaimer | AnyHVAC",
  description:
    "Important limitations and user responsibilities for AnyHVAC calculators, technical information, and design-assistance tools.",
};

export default function EngineeringDisclaimerPage() {
  return (
    <LegalPageShell
      title="Engineering Disclaimer"
      intro="Important information about the proper use and limitations of AnyHVAC calculators, technical information, and design-assistance tools."
    >
      <ContentSection title="1. Informational and Design-Assistance Purposes">
        <p>
          AnyHVAC provides HVAC calculators, reference materials, technical
          information, and other tools for informational, educational, and
          design-assistance purposes.
        </p>
        <p>
          AnyHVAC is intended to assist users with common HVAC calculations and
          technical workflows. It is not a substitute for professional engineering
          judgment, project-specific analysis, applicable codes and standards,
          manufacturer requirements, or review by the applicable authority having
          jurisdiction.
        </p>
        <p>
          Results generated by AnyHVAC should be independently reviewed and verified
          before being used for professional, design, construction, installation,
          permitting, procurement, equipment-selection, operation, maintenance, or
          other safety-critical purposes.
        </p>
      </ContentSection>

      <ContentSection title="2. User Responsibility">
        <p>
          Users are responsible for determining whether a calculation, method,
          assumption, input, output, reference, or other information provided through
          AnyHVAC is appropriate for their particular application.
        </p>
        <p>Before relying on an AnyHVAC result, users should verify, as applicable:</p>
        <ul>
          <li>Input values and units</li>
          <li>Calculation assumptions and methodology</li>
          <li>Resulting values and units</li>
          <li>Project-specific design conditions</li>
          <li>Applicable building, mechanical, energy, fire, and other codes</li>
          <li>Local amendments and requirements of the authority having jurisdiction</li>
          <li>Current manufacturer data, installation instructions, and equipment limitations</li>
          <li>Requirements imposed by a licensed design professional, owner, contractor, manufacturer, or other responsible party</li>
        </ul>
        <p>
          The user remains responsible for final engineering, design, equipment
          selection, installation, and construction decisions made using information
          obtained through AnyHVAC.
        </p>
      </ContentSection>

      <ContentSection title="3. Calculation Accuracy and Limitations">
        <p>
          We aim to make AnyHVAC calculations practical, transparent, and accurate.
          However, no calculator or software tool can account for every project
          condition or application.
        </p>
        <p>
          Calculations may rely on simplified engineering relationships, assumptions,
          approximations, default values, rounding, user-provided information, or
          generally accepted calculation methods.
        </p>
        <p>
          AnyHVAC does not warrant that calculations or results will be error-free,
          complete, appropriate for every application, or consistent with every
          jurisdiction, design standard, manufacturer requirement, or project
          specification.
        </p>
        <p>
          Users should independently verify important results using appropriate
          engineering methods, authoritative references, manufacturer documentation,
          or qualified professional review. If you believe a calculation is incorrect,
          please report the issue through the AnyHVAC <Link href="/contact">Contact page</Link>.
        </p>
      </ContentSection>

      <ContentSection title="4. No Professional Engineering Relationship">
        <p>
          Use of AnyHVAC does not create an engineer-client, consultant-client,
          contractor-client, architect-client, or other professional relationship
          between the user and AnyHVAC or the individuals involved in developing or
          maintaining AnyHVAC.
        </p>
        <p>
          AnyHVAC does not provide project-specific professional engineering services
          through general use of its website or calculators.
        </p>
        <p>
          Nothing presented by AnyHVAC should be interpreted as a professional seal,
          certification, approval, or representation that a particular design complies
          with applicable professional, contractual, regulatory, or permitting requirements.
        </p>
        <p>
          Where professional engineering services or a licensed professional are
          required by law, contract, regulation, project scope, or the authority having
          jurisdiction, users are responsible for obtaining those services.
        </p>
      </ContentSection>

      <ContentSection title="5. Codes, Standards, and Regulations">
        <p>
          AnyHVAC may provide references, summaries, links, navigation tools, or
          educational information related to building codes, mechanical codes,
          standards, regulations, and other technical requirements. Such information
          is provided for convenience and general informational purposes.
        </p>
        <p>
          Codes and standards may be revised, replaced, amended, interpreted
          differently, or modified by state and local jurisdictions. Online information
          may also become outdated.
        </p>
        <p>
          Users are responsible for verifying requirements against the current official
          source, applicable local amendments, project requirements, and the authority
          having jurisdiction before relying on them. A reference or link provided by
          AnyHVAC should not be interpreted as a determination that a particular code
          provision applies to a specific project.
        </p>
      </ContentSection>

      <ContentSection title="6. Manufacturer and Equipment Information">
        <p>
          AnyHVAC may provide links, references, comparisons, selection assistance, or
          other information concerning HVAC equipment, products, and manufacturers.
          Manufacturer information can change without notice.
        </p>
        <p>
          Users should verify equipment capacities, performance data, dimensions,
          electrical requirements, operating limits, compatibility, installation
          requirements, availability, certifications, and other relevant characteristics
          directly against the manufacturer&apos;s current official documentation before
          selecting, purchasing, specifying, or installing equipment.
        </p>
        <p>
          Any equipment-selection functionality provided by AnyHVAC should be considered
          an assistance tool and not a final equipment selection or engineering approval.
        </p>
      </ContentSection>

      <ContentSection title="7. Advertising, Sponsorships, Affiliates, and Independence">
        <p>
          AnyHVAC may be supported through voluntary financial support, advertising,
          sponsorships, affiliate relationships, referral relationships, or other forms
          of monetization. These relationships do not determine or alter AnyHVAC
          calculation results or engineering outcomes.
        </p>
        <p>
          Paid relationships will not cause a calculator to change a calculated result
          or cause equipment to be represented as the preferred engineering choice
          solely because of advertising, sponsorship, affiliate compensation, or other
          payment. Where required or appropriate, commercial or affiliate relationships
          will be disclosed.
        </p>
      </ContentSection>

      <ContentSection title="8. Third-Party Resources and External Links">
        <p>
          AnyHVAC may link to websites, documents, manufacturer resources, government
          resources, standards organizations, software, or other third-party materials.
          These links are provided for convenience and informational purposes.
        </p>
        <p>
          AnyHVAC does not control third-party websites and cannot guarantee their
          accuracy, availability, security, completeness, or continued accessibility.
          A link to a third-party resource does not necessarily constitute endorsement
          of that organization, product, service, interpretation, or content.
        </p>
      </ContentSection>

      <ContentSection title="9. No Warranty">
        <p>
          To the extent permitted by applicable law, AnyHVAC and its content,
          calculators, tools, and resources are provided &quot;as is&quot; and &quot;as available.&quot;
        </p>
        <p>
          We do not make guarantees regarding uninterrupted availability, completeness,
          accuracy, reliability, suitability for a particular project, or freedom from
          errors. AnyHVAC may modify, correct, add, remove, suspend, or discontinue
          tools, calculations, features, references, or content at any time.
        </p>
      </ContentSection>

      <ContentSection title="10. Limitation of Liability">
        <p>
          To the extent permitted by applicable law, AnyHVAC and the persons involved in
          creating, operating, or maintaining it will not be liable for indirect,
          incidental, special, consequential, or similar damages arising from reliance
          on or use of the website, calculators, results, references, external links, or
          other content.
        </p>
        <p>
          Users remain responsible for independently reviewing and verifying information
          before applying it to real-world engineering, construction, equipment-selection,
          installation, or operational decisions. Nothing in this disclaimer is intended
          to exclude or limit liability that cannot lawfully be excluded or limited under
          applicable law.
        </p>
      </ContentSection>

      <ContentSection title="11. Safety-Critical Applications">
        <p>
          AnyHVAC calculations should not be relied upon as the sole basis for decisions
          involving life safety, hazardous materials, critical environments, fire or
          smoke control, medical facilities, industrial process safety, or other
          applications where calculation or design failure could reasonably result in
          serious injury, death, significant property damage, or environmental harm.
        </p>
        <p>
          Such applications require appropriate project-specific analysis and qualified
          professional review.
        </p>
      </ContentSection>

      <ContentSection title="12. Changes to This Disclaimer">
        <p>
          AnyHVAC may update this Engineering Disclaimer as the website, available
          tools, applicable technologies, or services evolve. The Last Updated date at
          the top identifies the most recent revision. Continued use of AnyHVAC after an
          update is subject to the then-current version of this disclaimer.
        </p>
      </ContentSection>
    </LegalPageShell>
  );
}
